### ISSUE TITLE
Use with Activeform

### ISSUE THREAD

**Issue by dbd5** [schnz/yii2-bar-rating#1]
Hello,

How do you use this with activeform and a model?

Regards,

Adam

**Comment by schnz** [comment]
Hi Adam,

sorry for the late answer. I just saw your issue.
BarRating extends \yii\widgets\InputWidget, so you can use it like any other InputWidget:

``` php
<?= $form->field($model, 'rating')->widget(\coksnuss\widgets\barrating\BarRating::class, [
    // configure additional widget properties here
]) ?>
```

**Comment by dbd5** [comment]
Great, thanks
